import { ArrowLeftIcon } from '@heroicons/react/outline';
import Head from 'next/head';
import CommentModal from '../../components/CommentModal';
import Sidebar from '../../components/Sidebar';
import Widgets from '../../components/Widgets';
import Post from '../../components/Post';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { doc, onSnapshot } from 'firebase/firestore';
import { db } from '../../firebase';

export default function PostPage({ newsResults, randomUserResults }) {
  const router = useRouter();
  const { id } = router.query;
  const [post, setPost] = useState();

  useEffect(
    () => {onSnapshot(doc(db, 'posts', id)),
    (snapshot) => setPost(snapshot)}, [db, id]
  );
  return (
    <div>
      <Head>
        <title>Post page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* sidebar */}
        <Sidebar />

        {/* feed section */}
        <div className="xl:ml-[370px] border-l border-r min xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl border-gray-200">
          <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div className="hoverEffect" onClick={() => router.push("/")}>
              <ArrowLeftIcon className="h-5 " />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Post
            </h2>
          </div>
          <Post id={id} post={post} />
        </div>

        {/* widget */}
        <Widgets
          newsResults={newsResults.articles}
          randomUserResults={randomUserResults.results}
        />

        {/* modal */}

        <CommentModal />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const newsResults = await fetch(
    'https://saurav.tech/NewsAPI/top-headlines/category/business/us.json'
  ).then((res) => res.json());

  // who to follow section

  const randomUserResults = await fetch(
    'https://randomuser.me/api/?results=30&inc=name,login,picture'
  ).then((res) => res.json());
  return {
    props: {
      newsResults,
      randomUserResults,
    },
  };
}
